type ProviderRecord = Record<string, { create: string }>

export const SUPPORTED_PROVIDERS = {
  '@ai-sdk/openai': { create: 'createOpenAI' },
  '@ai-sdk/openai-compatible': { create: 'createOpenAICompatible' },
  '@ai-sdk/anthropic': { create: 'createAnthropic' },
  '@ai-sdk/google': { create: 'createGoogleGenerativeAI' },
  '@ai-sdk/xai': { create: 'createXai' },
  '@ai-sdk/azure': { create: 'createAzure' },
  '@ai-sdk/amazon-bedrock': { create: 'createAmazonBedrock' },
  '@ai-sdk/groq': { create: 'createGroq' },
  '@ai-sdk/fal': { create: 'createFal' },
  '@ai-sdk/deepinfra': { create: 'createDeepInfra' },
  '@ai-sdk/google-vertex': { create: 'createVertex' },
  '@ai-sdk/mistral': { create: 'createMistral' },
  '@ai-sdk/togetherai': { create: 'createTogetherAI' },
  '@ai-sdk/cohere': { create: 'createCohere' },
  '@ai-sdk/fireworks': { create: 'createFireworks' },
  '@ai-sdk/deepseek': { create: 'createDeepSeek' },
  '@ai-sdk/cerebras': { create: 'createCerebras' },
  '@ai-sdk/perplexity': { create: 'createPerplexity' },
  '@ai-sdk/luma': { create: 'createLuma' },
  '@ai-sdk/baseten': { create: 'createBaseten' },
  '@openrouter/ai-sdk-provider': { create: 'createOpenRouter' },
} as const satisfies ProviderRecord
